### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by Bradleyp123** [Nebula-Developer/Yoru-Engine#18]
You can use the CUDA Toolkit to write C++ (and C# if i remember correctly) scripts that can use the gpu. This could be helpful for a Lightmap Compiler or maybe memory (as Newer GPU's have Lots of VRAM). The only problem i can think of as of now is the lack of IGPU Support (I.E intel HD series / UHD. Im not sure about VEGA, IRIS-XE) and maybe poor support or lack of support for ARC GPU's (Intels attempt at a actual DGPU, in a while at least).
and maybe Matrox GPU's (Should be fine as they are mostly AMD based).

**Comment by Nebula-Developer** [comment]
Because CUDA is more suited for software that intentionally targets NVIDIA GPUs, I don't plan to implement it as it does not match with the cross-platform goals I have for Yoru Engine. One alternate option could be to make use of OpenCL, but it isn't really a goal for the current state of the framework, even long-term.
